# Copyright 2018-present Sonatype Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    ldflags:
      - -s -w -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildVersion={{.Version}}"
      - -s -w -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildTime={{time "2006-01-02T15:04:05Z07:00"}}"
      - -s -w -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildCommit={{.FullCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archives:
  - 
    id: default
    name_template: "{{ .ProjectName }}-{{ .Os }}.{{ .Arch }}-v{{ .Version }}"
    format: binary
  -
    id: homebrew
    name_template: "{{ .ProjectName }}-{{ .Os }}.{{ .Arch }}-v{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next-{{.FullCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  ids:
    - default
    - homebrew
  github:
    owner: sonatype-nexus-community
    name: nancy

brews:
  -
    ids:
      - homebrew
    github:
      owner: sonatype-nexus-community
      name: homebrew-nancy-tap

    homepage: https://github.com/sonatype-nexus-community/nancy
    description: "A tool to check for vulnerabilities in your Golang dependencies, powered by Sonatype OSS Index"

dockers:
  - 
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
    - "--label=author='DJ Schleen'"
    - "--label=version={{ .Version }}"
    - "--label=maintainer='sonatype-nexus-community'"
    image_templates:
    - "sonatypecommunity/nancy:latest"
    - "sonatypecommunity/nancy:{{ .Tag }}"
    - "sonatypecommunity/nancy:v{{ .Major }}"
    - "sonatypecommunity/nancy:v{{ .Major }}.{{ .Minor }}"
