# Copyright 2018-present Sonatype Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

before:
  hooks:
    - go mod download
    - go mod tidy -compat=1.17
builds:
  -
    ldflags:
      - -s -w
        -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildVersion={{.Version}}"
        -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildTime={{time "2006-01-02T15:04:05Z07:00"}}"
        -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildCommit={{.FullCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      # fix for build error:
      # тип release failed after 124.25s error=failed to build for windows_arm64: exit status 2: # golang.org/x/sys/windows
      #/go/pkg/mod/golang.org/x/sys@v0.0.0-20200519105757-fe76b779f299/windows/zsyscall_windows.go:2833:38: undefined: WSAData
      #/go/pkg/mod/golang.org/x/sys@v0.0.0-20200519105757-fe76b779f299/windows/zsyscall_windows.go:3106:51: undefined: Servent
      #/go/pkg/mod/golang.org/x/sys@v0.0.0-20200519105757-fe76b779f299/windows/zsyscall_windows.go:3120:50: undefined: Servent
      - goos: windows
        goarch: arm64

archives:
  -
    id: default
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
  -
    id: homebrew
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Version }}-next-{{.FullCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  ids:
    - default
    - homebrew
  github:
    owner: sonatype-nexus-community
    name: nancy

brews:
  -
    ids:
      - homebrew
    tap:
      owner: sonatype-nexus-community
      name: homebrew-nancy-tap

    homepage: https://github.com/sonatype-nexus-community/nancy
    description: "A tool to check for vulnerabilities in your Golang dependencies, powered by Sonatype OSS Index"

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    ids:
      - nancy
    build_flag_templates:
    - "--label=author='DJ Schleen'"
    - "--label=version={{ .Version }}"
    - "--label=maintainer='sonatype-nexus-community'"
    image_templates:
    - "sonatypecommunity/nancy:latest"
    - "sonatypecommunity/nancy:{{ .Tag }}"
    - "sonatypecommunity/nancy:v{{ .Major }}"
    - "sonatypecommunity/nancy:v{{ .Major }}.{{ .Minor }}"
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.alpine
    ids:
      - nancy
    build_flag_templates:
    - "--pull"
    - "--label=author='DJ Schleen'"
    - "--label=version={{ .Version }}"
    - "--label=maintainer='sonatype-nexus-community'"
    image_templates:
    - "sonatypecommunity/nancy:alpine"
    - "sonatypecommunity/nancy:{{ .Tag }}-alpine"
    - "sonatypecommunity/nancy:v{{ .Major }}-alpine"
    - "sonatypecommunity/nancy:v{{ .Major }}.{{ .Minor }}-alpine"

nfpms:
  -
    vendor: sonatype-nexus-community
    maintainer: Sonatype Nexus Community <community-group@sonatype.com>
    homepage: https://github.com/sonatype-nexus-community/nancy
    description: "A tool to check for vulnerabilities in your Golang dependencies, powered by Sonatype OSS Index"
    formats:
      - apk
      - deb
      - rpm
