before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    ldflags:
      - -s -w
        -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildVersion={{.Version}}"
        -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildTime={{time "2006-01-02T15:04:05Z07:00"}}"
        -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildCommit={{.FullCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archives:
  -
    id: default
    name_template: "{{ .ProjectName }}-{{ .Os }}.{{ .Arch }}-v{{ .Version }}"
    format: binary
  -
    id: homebrew
    name_template: "{{ .ProjectName }}-{{ .Os }}.{{ .Arch }}-v{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Version }}-next-{{.FullCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  ids:
    - default
    - homebrew
  github:
    owner: sonatype-nexus-community
    name: nancy

brews:
  -
    ids:
      - homebrew
    github:
      owner: sonatype-nexus-community
      name: homebrew-nancy-tap

    homepage: https://github.com/sonatype-nexus-community/nancy
    description: "A tool to check for vulnerabilities in your Golang dependencies, powered by Sonatype OSS Index"

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: build/Dockerfile
    binaries:
    - nancy
    build_flag_templates:
    - "--pull"
    - "--label=author='DJ Schleen'"
    - "--label=version={{ .Version }}"
    - "--label=maintainer='sonatype-nexus-community'"
    image_templates:
    - "sonatypecommunity/nancy:latest"
    - "sonatypecommunity/nancy:{{ .Tag }}"
    - "sonatypecommunity/nancy:v{{ .Major }}"
    - "sonatypecommunity/nancy:v{{ .Major }}.{{ .Minor }}"
  -
    goos: linux
    goarch: amd64
    dockerfile: build/Dockerfile.alpine
    binaries:
    - nancy
    build_flag_templates:
    - "--pull"
    - "--label=author='DJ Schleen'"
    - "--label=version={{ .Version }}"
    - "--label=maintainer='sonatype-nexus-community'"
    image_templates:
    - "sonatypecommunity/nancy:alpine"
    - "sonatypecommunity/nancy:{{ .Tag }}-alpine"
    - "sonatypecommunity/nancy:v{{ .Major }}-alpine"
    - "sonatypecommunity/nancy:v{{ .Major }}.{{ .Minor }}-alpine"
