before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    ldflags:
      - -s -w -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildVersion={{.Version}}"
      - -s -w -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildTime={{time "2006-01-02T15:04:05Z07:00"}}"
      - -s -w -X "github.com/sonatype-nexus-community/nancy/buildversion.BuildCommit={{.FullCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Os }}.{{ .Arch }}-v{{ .Version }}"
    format: binary

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next-{{.FullCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: sonatype-nexus-community
    name: nancy
